# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Documentation 1"
  url = "docs1/"
  weight = 10

[[main]]
  name = "Documentation 2"
  url = "docs2/"
  weight = 20